services:
  bot:
    build: .
    container_name: my-tg-bot
    env_file:
      - .env
    volumes:
      - ./media:/app/media
    # Эта команда не дает контейнеру завершиться, чтобы мы могли войти внутрь для отладки.
    # command: ["tail", "-f", "/dev/null"]
